// Mocks generated by Mockito 5.4.6 from annotations
// in pos_kasir_flutter/test/providers/cart_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pos_kasir_flutter/services/dio_client.dart' as _i2;
import 'package:pos_kasir_flutter/services/product_service.dart' as _i5;
import 'package:pos_kasir_flutter/services/sale_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SaleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaleService extends _i1.Mock implements _i3.SaleService {
  MockSaleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient =>
      (super.noSuchMethod(
            Invocation.getter(#dioClient),
            returnValue: _FakeDioClient_0(this, Invocation.getter(#dioClient)),
          )
          as _i2.DioClient);

  @override
  _i4.Future<Map<String, dynamic>> createSale({int? paymentId}) =>
      (super.noSuchMethod(
            Invocation.method(#createSale, [], {#paymentId: paymentId}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> addItem({
    required int? saleId,
    required int? productId,
    int? quantity = 1,
    double? discountAmount = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [], {
              #saleId: saleId,
              #productId: productId,
              #quantity: quantity,
              #discountAmount: discountAmount,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> removeItem(int? saleItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [saleItemId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateItemQuantity({
    required int? saleId,
    required int? saleItemId,
    required int? productId,
    required int? newQuantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemQuantity, [], {
              #saleId: saleId,
              #saleItemId: saleItemId,
              #productId: productId,
              #newQuantity: newQuantity,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getSale(int? saleId) =>
      (super.noSuchMethod(
            Invocation.method(#getSale, [saleId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> completeSale({
    required int? saleId,
    required int? paymentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeSale, [], {
              #saleId: saleId,
              #paymentId: paymentId,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deleteSale(int? saleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSale, [saleId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i5.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient =>
      (super.noSuchMethod(
            Invocation.getter(#dioClient),
            returnValue: _FakeDioClient_0(this, Invocation.getter(#dioClient)),
          )
          as _i2.DioClient);

  @override
  _i4.Future<Map<String, dynamic>> getProducts({
    int? categoryId,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #categoryId: categoryId,
              #search: search,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [productId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> searchByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#searchByBarcode, [barcode]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
